name: "Environment variables to file"
description: "Get AWS parameters and secrets and create a file"
inputs:
  parameters-path:
    description: "Path of parameters of parameter store"
    required: false
    default: ""
  secrets-path:
    description: "Path of secrets of secret manager"
    required: false
    default: ""
  file-name:
    description: "Name of file (default is .env)"
    required: false
    default: ".env"
outputs:
  file:
    description: "The generate file path"
    value: ${{ github.action_path }}/${{ inputs.file-name }}
runs:
  using: "composite"
  steps:
    - run: |
        source ${{ github.action_path }}/envs-to-file.sh ${{ inputs.parameters-path }} ${{ inputs.secrets-path }} ${{ inputs.file-name }}
        env >> $GITHUB_ENV
      shell: bash
